### ISSUE TITLE
Hi Mayank, how can i use the unzip function

### ISSUE THREAD

**Issue by Tanusarswal** [mayank1897/Activity-Recognition-from-a-Single-Chest-Mounted-Accelerometer#1]
Can you please guide me how to use the unzip function in your code. i am working on a project for one of my subject in uni and i am taking reference from your work. I have tried everything but i can't find something relevant to unzip function. spyder is throwing an error 'unzip' is not recognized as an internal or external command,
operable program or batch file.  I did not know the other option to reach you.
I will be very thankful

**Comment by mayank1897** [comment]
@Tanusarswal Spyder is showing that error because it's a magic function used in notebooks (Jupyter, Google Colab, etc ) only not in IDE's like spyder.
Kindly check this reference for getting out from unzip function issue.
" https://www.geeksforgeeks.org/working-zip-files-python/ "

**Comment by Tanusarswal** [comment]
Hi Mayank,

Thank you for your reply but I can’t open that link it is saying, can’t
find the server.
I want to thank you one more time for replying
To a new comer in python and data science.

Regards,
Tanu

**Comment by mayank1897** [comment]
HI @Tanusarswal ,
you can use the module zipfile for this.

Regards,
Mayank Choudhary

**Comment by Tanusarswal** [comment]
Thank you mayank.
